### ISSUE TITLE
[FEATURE] Make `CRUD` Operations For Posts

### ISSUE THREAD

**Issue by Seifeldin-Ahmed** [Seifeldin-Ahmed/Social-Media-Platform#9]
CRUD: Create Read Update Delete

**Comment by azilRababe** [comment]
Hi! I'd like to work on this issue. Could you please assign it to me? Also, could you provide a bit more detail on what you’d like to see in the solution?

**Comment by Seifeldin-Ahmed** [comment]
Sorry but the project still under our development and external
contributions will be allowed after finishing the fundmentals
